
import os

tag_map = {
    '<asp:Label': 'global::System.Web.UI.WebControls.Label',
    '<asp:TextBox': 'global::System.Web.UI.WebControls.TextBox',
    '<asp:Button': 'global::System.Web.UI.WebControls.Button',
    '<asp:LinkButton': 'global::System.Web.UI.WebControls.LinkButton',
    '<asp:ImageButton': 'global::System.Web.UI.WebControls.ImageButton',
    '<asp:HyperLink': 'global::System.Web.UI.WebControls.HyperLink',
    '<asp:DropDownList': 'global::System.Web.UI.WebControls.DropDownList',
    '<asp:ListBox': 'global::System.Web.UI.WebControls.ListBox',
    '<asp:CheckBox': 'global::System.Web.UI.WebControls.CheckBox',
    '<asp:CheckBoxList': 'global::System.Web.UI.WebControls.CheckBoxList',
    '<asp:RadioButton': 'global::System.Web.UI.WebControls.RadioButton',
    '<asp:RadioButtonList': 'global::System.Web.UI.WebControls.RadioButtonList',
    '<asp:Image': 'global::System.Web.UI.WebControls.Image',
    '<asp:Table': 'global::System.Web.UI.WebControls.Table',
    '<asp:TableRow': 'global::System.Web.UI.WebControls.TableRow',
    '<asp:TableCell': 'global::System.Web.UI.WebControls.TableCell',
    '<asp:Panel': 'global::System.Web.UI.WebControls.Panel',
    '<asp:PlaceHolder': 'global::System.Web.UI.WebControls.PlaceHolder',
    '<asp:Calendar': 'global::System.Web.UI.WebControls.Calendar',
    '<asp:AdRotator': 'global::System.Web.UI.WebControls.AdRotator',
    '<asp:Xml': 'global::System.Web.UI.WebControls.Xml',
    '<asp:Literal': 'global::System.Web.UI.WebControls.Literal',
    '<asp:HiddenField': 'global::System.Web.UI.WebControls.HiddenField',
    '<asp:FileUpload': 'global::System.Web.UI.WebControls.FileUpload',
    '<asp:Wizard': 'global::System.Web.UI.WebControls.Wizard',
    '<asp:MultiView': 'global::System.Web.UI.WebControls.MultiView',
    '<asp:View': 'global::System.Web.UI.WebControls.View',
    '<asp:Localize': 'global::System.Web.UI.WebControls.Localize',
    '<asp:GridView': 'global::System.Web.UI.WebControls.GridView',
    '<asp:DetailsView': 'global::System.Web.UI.WebControls.DetailsView',
    '<asp:FormView': 'global::System.Web.UI.WebControls.FormView',
    '<asp:Repeater': 'global::System.Web.UI.WebControls.Repeater',
    '<asp:DataList': 'global::System.Web.UI.WebControls.DataList',
    '<asp:ScriptManager': 'global::System.Web.UI.ScriptManager',
    '<asp:UpdatePanel': 'global::System.Web.UI.UpdatePanel',
    '<asp:UpdateProgress': 'global::System.Web.UI.UpdateProgress',
    '<asp:Timer': 'global::System.Web.UI.Timer',
    # User Controls
    '<uc1:cabecalho': 'SILC.Web.forms.cabecalho',
    '<uc2:menu': 'SILC.Web.forms.menu',
    '<uc1:INTEIRO7': 'SILC.Web.forms.forms_INTEIRO7',
    '<uc4:INTEIRO7': 'SILC.Web.forms.forms_INTEIRO7',
    '<uc3:INTEIRO': 'SILC.Web.forms.forms_INTEIRO',
    '<uc5:MOEDA': 'SILC.Web.forms.forms_MOEDA',
    '<uc6:DATA': 'SILC.Web.forms.forms_DATA',
    '<uc9:INTEIRO2': 'SILC.Web.forms.forms_Inteiro2',
    '<uc7:GRUPORESIDUO': 'SILC.Web.forms.forms_GRUPORESIDUO',
    '<uc8:DESTINOFINAL': 'SILC.Web.forms.forms_DESTINOFINAL',
}

files_config = [
    {
        'control_file': 'controls_ConfigSis.txt',
        'output_file': 'forms/ConfigSis.aspx.designer.cs',
        'namespace': 'SILC.Web.forms',
        'classname': 'ConfigSis'
    },
    {
        'control_file': 'controls_CodigosServicosPrefeitura.txt',
        'output_file': 'forms/CodigosServicosPrefeitura.aspx.designer.cs',
        'namespace': 'SILC.Web.forms',
        'classname': 'CodigosServicosPrefeitura'
    },
    {
        'control_file': 'controls_Containeres.txt',
        'output_file': 'forms/Containeres.aspx.designer.cs',
        'namespace': 'SILC.Web.forms',
        'classname': 'forms_containeres'
    },
    {
        'control_file': 'controls_ClientesHistorico.txt',
        'output_file': 'forms/ClientesHistorico.aspx.designer.cs',
        'namespace': 'SILC.Web.forms',
        'classname': 'webClientesHistorico'
    },
    {
        'control_file': 'controls_ClientesIncluir.txt',
        'output_file': 'forms/Clientes_Incluir.aspx.designer.cs',
        'namespace': 'SILC.Web.forms',
        'classname': 'webClientesIncluir'
    }
]

for config in files_config:
    with open(config['control_file'], 'r') as f:
        lines = f.readlines()

    content = f"""//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace {config['namespace']} {{
    
    
    public partial class {config['classname']} {{
"""
    
    seen_ids = set()
    for line in lines:
        parts = line.strip().split()
        if len(parts) >= 2:
            tag = parts[0]
            ctrl_id = parts[1]
            
            if ctrl_id in seen_ids:
                continue
            seen_ids.add(ctrl_id)

            if tag in tag_map:
                type_name = tag_map[tag]
                content += f"""
        /// <summary>
        /// {ctrl_id} control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected {type_name} {ctrl_id};
"""
            else:
                # Handle unknown tags or generic fallback
                print(f"Warning: Unknown tag {tag} for control {ctrl_id} in {config['control_file']}")

    content += """    }
}
"""
    
    with open(config['output_file'], 'w') as f:
        f.write(content)
    
    print(f"Generated {config['output_file']}")
