namespace SILC.Web.forms {
    public partial class webClientes {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::SILC.Web.forms.cabecalho cabecalho1;
        protected global::SILC.Web.forms.menu menucabec1;
        protected global::System.Web.UI.WebControls.Label lblTitulo;
        protected global::System.Web.UI.WebControls.GridView Grade;
        protected global::System.Web.UI.WebControls.Label lblFiltro;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltro;
        protected global::System.Web.UI.WebControls.TextBox txtFiltro;
        protected global::System.Web.UI.WebControls.Button btnOk;
        protected global::System.Web.UI.WebControls.Button btnDocumentacaoAplicavel;
        protected global::System.Web.UI.WebControls.Menu Menu1;
        protected global::System.Web.UI.WebControls.Label lblTituloCodigoCliente;
        protected global::System.Web.UI.WebControls.Label lblCodigoCliente;
        protected global::System.Web.UI.WebControls.MultiView MultiView1;
        protected global::System.Web.UI.WebControls.View ViewDados;
        protected global::System.Web.UI.WebControls.Label lblNovaSenha0;
        protected global::SILC.Web.forms.DATA datDataCadastro;
        protected global::System.Web.UI.WebControls.CheckBox chkNaoAceitaDTRComPesoDiferente;
        protected global::System.Web.UI.WebControls.ImageButton imbInativo;
        protected global::System.Web.UI.WebControls.Label lblInativo;
        protected global::System.Web.UI.WebControls.Label lblTipoCadastro;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCadastro;
        protected global::System.Web.UI.WebControls.Label Label9;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoAterro;
        protected global::System.Web.UI.WebControls.Label lblNome;
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        protected global::System.Web.UI.WebControls.Label Label52;
        protected global::SILC.Web.forms.INTEIRO intCodigoFuncionarioComercial;
        protected global::System.Web.UI.WebControls.Label lblNomeFuncionario;
        protected global::System.Web.UI.WebControls.Label Label58;
        protected global::System.Web.UI.WebControls.GridView GradeHistorico;
        protected global::System.Web.UI.WebControls.Label lblNomeFantasia;
        protected global::System.Web.UI.WebControls.TextBox txtNomeFantasia;
        protected global::System.Web.UI.WebControls.Label lblNovaSenha2;
        protected global::System.Web.UI.WebControls.TextBox txtNovaSenha;
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.TextBox txtCNPJ_CPF;
        protected global::System.Web.UI.WebControls.TextBox txtAlfaCNPJ_CPF;
        protected global::System.Web.UI.WebControls.Label lblNovaSenha3;
        protected global::SILC.Web.forms.DATA datDataNovaSenha;
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.TextBox txtRG_IE;
        protected global::System.Web.UI.WebControls.Label lblSolicitadaPor;
        protected global::System.Web.UI.WebControls.TextBox txtSolicitadaPor;
        protected global::System.Web.UI.WebControls.Label Label3;
        protected global::SILC.Web.forms.INTEIRO7 intClassificacao;
        protected global::System.Web.UI.WebControls.Label Label7;
        protected global::SILC.Web.forms.INTEIRO7 intFilial;
        protected global::System.Web.UI.WebControls.Label Label10;
        protected global::SILC.Web.forms.INTEIRO7 intContaGerencial;
        protected global::System.Web.UI.WebControls.Label Label8;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoExpNF;
        protected global::System.Web.UI.WebControls.CheckBox chkEmiteDDR;
        protected global::System.Web.UI.WebControls.CheckBox chkEmitirCDF;
        protected global::System.Web.UI.WebControls.Button Salvar;
        protected global::System.Web.UI.WebControls.Button btnAlterar;
        protected global::System.Web.UI.WebControls.Button Copiar;
        protected global::System.Web.UI.WebControls.Label lblMensagemCopiar;
        protected global::System.Web.UI.WebControls.Label Label55;
        protected global::System.Web.UI.WebControls.DropDownList ddlAliquotasFederais;
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        protected global::System.Web.UI.WebControls.HiddenField hifCodigo;
        protected global::System.Web.UI.WebControls.View ViewEnderecoPadrao;
        protected global::System.Web.UI.WebControls.Label lblEndereco0;
        protected global::System.Web.UI.WebControls.TextBox txtEndereco0;
        protected global::System.Web.UI.WebControls.Label lblNumero0;
        protected global::SILC.Web.forms.INTEIRO7 intNumero0;
        protected global::System.Web.UI.WebControls.Label lblComplemento0;
        protected global::System.Web.UI.WebControls.TextBox txtComplemento0;
        protected global::System.Web.UI.WebControls.Label lblFone10;
        protected global::SILC.Web.forms.INTEIRO2 intDDD10;
        protected global::System.Web.UI.WebControls.TextBox txtFone10;
        protected global::System.Web.UI.WebControls.Label lblBairro0;
        protected global::System.Web.UI.WebControls.TextBox txtBairro0;
        protected global::System.Web.UI.WebControls.Label lblFone20;
        protected global::SILC.Web.forms.INTEIRO2 intDDD20;
        protected global::System.Web.UI.WebControls.TextBox txtFone20;
        protected global::System.Web.UI.WebControls.Label lblCEP0;
        protected global::System.Web.UI.WebControls.TextBox txtCEP0;
        protected global::System.Web.UI.WebControls.Label lblUF0;
        protected global::System.Web.UI.WebControls.TextBox txtUF0;
        protected global::System.Web.UI.WebControls.Label lblCodigoIBGE0;
        protected global::System.Web.UI.WebControls.TextBox txtCodigoIBGE0;
        protected global::System.Web.UI.WebControls.Label lblCelular0;
        protected global::SILC.Web.forms.INTEIRO2 intDDDC0;
        protected global::System.Web.UI.WebControls.TextBox txtCelular0;
        protected global::System.Web.UI.WebControls.Label lblCidade0;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoClidade0;
        protected global::System.Web.UI.WebControls.TextBox lbtNomeCidade0;
        protected global::System.Web.UI.WebControls.Label lblFax0;
        protected global::SILC.Web.forms.INTEIRO2 intDDDF0;
        protected global::System.Web.UI.WebControls.TextBox txtFax0;
        protected global::System.Web.UI.WebControls.Label lblemail0;
        protected global::System.Web.UI.WebControls.TextBox txtemail0;
        protected global::System.Web.UI.WebControls.Label lblContato0;
        protected global::System.Web.UI.WebControls.TextBox txtContato0;
        protected global::System.Web.UI.WebControls.Button btnOk0;
        protected global::System.Web.UI.WebControls.Button btnAlterar0;
        protected global::System.Web.UI.WebControls.Label lblMensagem0;
        protected global::System.Web.UI.WebControls.HiddenField HiddenField1;
        protected global::System.Web.UI.WebControls.View ViewEnderecoFaturamento;
        protected global::System.Web.UI.WebControls.Label Label4;
        protected global::System.Web.UI.WebControls.TextBox txtEndereco1;
        protected global::System.Web.UI.WebControls.Label Label5;
        protected global::SILC.Web.forms.INTEIRO7 intNumero1;
        protected global::System.Web.UI.WebControls.Label Label6;
        protected global::System.Web.UI.WebControls.TextBox txtComplemento1;
        protected global::System.Web.UI.WebControls.Label Label11;
        protected global::SILC.Web.forms.INTEIRO2 intDDD11;
        protected global::System.Web.UI.WebControls.TextBox txtFone11;
        protected global::System.Web.UI.WebControls.Label Label12;
        protected global::System.Web.UI.WebControls.TextBox txtBairro1;
        protected global::System.Web.UI.WebControls.Label Label13;
        protected global::SILC.Web.forms.INTEIRO2 intDDD21;
        protected global::System.Web.UI.WebControls.TextBox txtFone21;
        protected global::System.Web.UI.WebControls.Label Label14;
        protected global::System.Web.UI.WebControls.TextBox txtCEP1;
        protected global::System.Web.UI.WebControls.Label Label15;
        protected global::System.Web.UI.WebControls.TextBox txtUF1;
        protected global::System.Web.UI.WebControls.Label Label16;
        protected global::System.Web.UI.WebControls.TextBox txtCodigoIBGE1;
        protected global::System.Web.UI.WebControls.Label Label17;
        protected global::SILC.Web.forms.INTEIRO2 intDDDC1;
        protected global::System.Web.UI.WebControls.TextBox txtCelular1;
        protected global::System.Web.UI.WebControls.Label Label18;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoClidade1;
        protected global::System.Web.UI.WebControls.TextBox lbtNomeCidade1;
        protected global::System.Web.UI.WebControls.Label Label19;
        protected global::SILC.Web.forms.INTEIRO2 intDDDF1;
        protected global::System.Web.UI.WebControls.TextBox txtFax1;
        protected global::System.Web.UI.WebControls.Label Label20;
        protected global::System.Web.UI.WebControls.TextBox txtemail1;
        protected global::System.Web.UI.WebControls.Label Label37;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCobranca;
        protected global::System.Web.UI.WebControls.Label Label54;
        protected global::System.Web.UI.WebControls.TextBox txtInstrucoesFaturamento;
        protected global::System.Web.UI.WebControls.Label Label53;
        protected global::System.Web.UI.WebControls.TextBox txtCNPJ_CPF_Faturamento;
        protected global::System.Web.UI.WebControls.TextBox txtAlfaCNPJ;
        protected global::System.Web.UI.WebControls.Label Label21;
        protected global::System.Web.UI.WebControls.TextBox txtContato1;
        protected global::System.Web.UI.WebControls.Button btnOk1;
        protected global::System.Web.UI.WebControls.Button btnAlterar1;
        protected global::System.Web.UI.WebControls.Label lblMensagem1;
        protected global::System.Web.UI.WebControls.HiddenField HiddenField2;
        protected global::System.Web.UI.WebControls.View ViewEnderecoColeta;
        protected global::System.Web.UI.WebControls.Label Label23;
        protected global::System.Web.UI.WebControls.TextBox txtEndereco2;
        protected global::System.Web.UI.WebControls.Label Label24;
        protected global::SILC.Web.forms.INTEIRO7 intNumero2;
        protected global::System.Web.UI.WebControls.Label Label25;
        protected global::System.Web.UI.WebControls.TextBox txtComplemento2;
        protected global::System.Web.UI.WebControls.Label Label26;
        protected global::SILC.Web.forms.INTEIRO2 intDDD12;
        protected global::System.Web.UI.WebControls.TextBox txtFone12;
        protected global::System.Web.UI.WebControls.Label Label27;
        protected global::System.Web.UI.WebControls.TextBox txtBairro2;
        protected global::System.Web.UI.WebControls.Label Label28;
        protected global::SILC.Web.forms.INTEIRO2 intDDD22;
        protected global::System.Web.UI.WebControls.TextBox txtFone22;
        protected global::System.Web.UI.WebControls.Label Label29;
        protected global::System.Web.UI.WebControls.TextBox txtCEP2;
        protected global::System.Web.UI.WebControls.Label Label30;
        protected global::System.Web.UI.WebControls.TextBox txtUF2;
        protected global::System.Web.UI.WebControls.Label Label31;
        protected global::System.Web.UI.WebControls.TextBox txtCodigoIBGE2;
        protected global::System.Web.UI.WebControls.Label Label32;
        protected global::SILC.Web.forms.INTEIRO2 intDDDC2;
        protected global::System.Web.UI.WebControls.TextBox txtCelular2;
        protected global::System.Web.UI.WebControls.Label Label33;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoClidade2;
        protected global::System.Web.UI.WebControls.TextBox lbtNomeCidade2;
        protected global::System.Web.UI.WebControls.Label Label34;
        protected global::SILC.Web.forms.INTEIRO2 intDDDF2;
        protected global::System.Web.UI.WebControls.TextBox txtFax2;
        protected global::System.Web.UI.WebControls.Label Label35;
        protected global::System.Web.UI.WebControls.TextBox txtemail2;
        protected global::System.Web.UI.WebControls.Label Label36;
        protected global::System.Web.UI.WebControls.TextBox txtContato2;
        protected global::System.Web.UI.WebControls.Label Label56;
        protected global::System.Web.UI.WebControls.TextBox txtCargoContato;
        protected global::System.Web.UI.WebControls.Button btnOk2;
        protected global::System.Web.UI.WebControls.Button btnAlterar2;
        protected global::System.Web.UI.WebControls.Label lblMensagem2;
        protected global::System.Web.UI.WebControls.HiddenField HiddenField3;
        protected global::System.Web.UI.WebControls.View ViewInformacoes;
        protected global::System.Web.UI.WebControls.Label Label39;
        protected global::SILC.Web.forms.INTEIRO7 intKmMedia;
        protected global::System.Web.UI.WebControls.Label Label22;
        protected global::System.Web.UI.WebControls.TextBox txtPontoDeReferencia;
        protected global::System.Web.UI.WebControls.Label Label40;
        protected global::System.Web.UI.WebControls.TextBox txtObservacao;
        protected global::System.Web.UI.WebControls.CheckBox chkIncluirAtualizarDados;
        protected global::System.Web.UI.WebControls.Label lblMensagem4;
        protected global::System.Web.UI.WebControls.HiddenField HiddenField4;
        protected global::System.Web.UI.WebControls.Button btnOkInformacoes;
        protected global::System.Web.UI.WebControls.Button btnAlterar3;
        protected global::System.Web.UI.WebControls.View ViewSistemaFatima;
        protected global::System.Web.UI.WebControls.Label lblTituloFatma;
        protected global::System.Web.UI.WebControls.Label Label43;
        protected global::System.Web.UI.WebControls.TextBox txtSenhaMaster;
        protected global::System.Web.UI.WebControls.Label lblSenhaAcesso;
        protected global::System.Web.UI.WebControls.TextBox txtSenhaAcesso;
        protected global::System.Web.UI.WebControls.Label lblObsMTRe;
        protected global::System.Web.UI.WebControls.TextBox txtObsMTRFatima;
        protected global::System.Web.UI.WebControls.HyperLink HyperLink1;
        protected global::System.Web.UI.WebControls.Label Label49;
        protected global::System.Web.UI.WebControls.TextBox txtContatoFatma;
        protected global::System.Web.UI.WebControls.Label Label50;
        protected global::System.Web.UI.WebControls.TextBox txtFoneFatma;
        protected global::System.Web.UI.WebControls.Label Label51;
        protected global::System.Web.UI.WebControls.TextBox txtemailFatma;
        protected global::System.Web.UI.WebControls.Label Label57;
        protected global::SILC.Web.forms.INTEIRO7 intCodigoUnidadeIMA;
        protected global::System.Web.UI.WebControls.CheckBox chkClienteExigeMTReParaRCD;
        protected global::System.Web.UI.WebControls.Button btnSalvarFatima;
        protected global::System.Web.UI.WebControls.Button btnAlterar4;
        protected global::System.Web.UI.WebControls.Label lblMensagem5;
        protected global::System.Web.UI.WebControls.HiddenField HiddenField5;
        protected global::System.Web.UI.WebControls.HiddenField hidEndereco0;
        protected global::System.Web.UI.WebControls.HiddenField hidNumero0;
        protected global::System.Web.UI.WebControls.HiddenField hidComplemento0;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD1_0;
        protected global::System.Web.UI.WebControls.HiddenField hidFone1_0;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD2_0;
        protected global::System.Web.UI.WebControls.HiddenField hidFone2_0;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD3_0;
        protected global::System.Web.UI.WebControls.HiddenField hidFone3_0;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD4_0;
        protected global::System.Web.UI.WebControls.HiddenField hidFone4_0;
        protected global::System.Web.UI.WebControls.HiddenField hidBairro0;
        protected global::System.Web.UI.WebControls.HiddenField hidCEP0;
        protected global::System.Web.UI.WebControls.HiddenField hidUF0;
        protected global::System.Web.UI.WebControls.HiddenField hidCodigoIBGE0;
        protected global::System.Web.UI.WebControls.HiddenField hidCodigoCidade0;
        protected global::System.Web.UI.WebControls.HiddenField hidEmail0;
        protected global::System.Web.UI.WebControls.HiddenField hidContato0;
        protected global::System.Web.UI.WebControls.HiddenField hidEndereco1;
        protected global::System.Web.UI.WebControls.HiddenField hidNumero1;
        protected global::System.Web.UI.WebControls.HiddenField hidComplemento1;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD1_1;
        protected global::System.Web.UI.WebControls.HiddenField hidFone1_1;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD2_1;
        protected global::System.Web.UI.WebControls.HiddenField hidFone2_1;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD3_1;
        protected global::System.Web.UI.WebControls.HiddenField hidFone3_1;
        protected global::System.Web.UI.WebControls.HiddenField hidDDD4_1;
        protected global::System.Web.UI.WebControls.HiddenField hidFone4_1;
        protected global::System.Web.UI.WebControls.HiddenField hidBairro1;
        protected global::System.Web.UI.WebControls.HiddenField hidCEP1;
        protected global::System.Web.UI.WebControls.HiddenField hidUF1;
        protected global::System.Web.UI.WebControls.HiddenField hidCodigoIBGE1;
        protected global::System.Web.UI.WebControls.HiddenField hidCodigoCidade1;
        protected global::System.Web.UI.WebControls.HiddenField hidEmail1;
        protected global::System.Web.UI.WebControls.HiddenField hidContato1;
        protected global::System.Web.UI.WebControls.Button btnProcurar;

        /// <summary>
        /// ibnMudarSernha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnMudarSernha;


        /// <summary>
        /// ibnExcluir control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnExcluir;


        /// <summary>
        /// ibnConsultaHistorico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnConsultaHistorico;

    }
}