//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILC.Web.forms {
    
    
    public partial class Account_DestinoFinal {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// cabecalho1 control.
        /// </summary>
        protected global::SILC.Web.forms.cabecalho cabecalho1;
        
        /// <summary>
        /// menucabec1 control.
        /// </summary>
        protected global::SILC.Web.forms.menu menucabec1;
        
        /// <summary>
        /// lblTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTitulo;
        
        /// <summary>
        /// Grade control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView Grade;
        
        /// <summary>
        /// Menu1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Menu Menu1;
        
        /// <summary>
        /// MultiView1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.MultiView MultiView1;
        
        /// <summary>
        /// ViewDados control.
        /// </summary>
        protected global::System.Web.UI.WebControls.View ViewDados;
        
        /// <summary>
        /// Label17 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label17;
        
        /// <summary>
        /// datDataCadastro control.
        /// </summary>
        protected global::SILC.Web.forms.DATA datDataCadastro;
        
        /// <summary>
        /// chkAtivo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAtivo;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// txtEndereco control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndereco;
        
        /// <summary>
        /// Label9 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label9;
        
        /// <summary>
        /// txtBairro control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBairro;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// txtNome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        
        /// <summary>
        /// Label15 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label15;
        
        /// <summary>
        /// intCEP control.
        /// </summary>
        protected global::SILC.Web.forms.INTEIRO7 intCEP;
        
        /// <summary>
        /// Label3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// txtNomeFantasia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNomeFantasia;
        
        /// <summary>
        /// Label10 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label10;
        
        /// <summary>
        /// txtCidade control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCidade;
        
        /// <summary>
        /// Label11 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label11;
        
        /// <summary>
        /// txtUF control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUF;
        
        /// <summary>
        /// lblNovaSenha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNovaSenha;
        
        /// <summary>
        /// txtCNPJ control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCNPJ;
        
        /// <summary>
        /// Label12 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label12;
        
        /// <summary>
        /// lblConfirmaNovaSenha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConfirmaNovaSenha;
        
        /// <summary>
        /// txtTelefone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefone;
        
        /// <summary>
        /// txtNomeArqLogo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNomeArqLogo;
        
        /// <summary>
        /// Label5 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label5;
        
        /// <summary>
        /// txtCelular control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCelular;
        
        /// <summary>
        /// Label16 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label16;
        
        /// <summary>
        /// Label6 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label6;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        /// <summary>
        /// txtNomeArqAss control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNomeArqAss;
        
        /// <summary>
        /// Label7 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label7;
        
        /// <summary>
        /// txtLocalAterro control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLocalAterro;
        
        /// <summary>
        /// chkEnviarEmailCDF control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEnviarEmailCDF;
        
        /// <summary>
        /// chkEnviarMovResiduos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEnviarMovResiduos;
        
        /// <summary>
        /// chkEmiteCDF control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEmiteCDF;
        
        /// <summary>
        /// Label21 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label21;
        
        /// <summary>
        /// intCodUnidadeIMA control.
        /// </summary>
        protected global::SILC.Web.forms.INTEIRO7 intCodUnidadeIMA;
        
        /// <summary>
        /// hifCodigo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hifCodigo;
        
        /// <summary>
        /// lblMensagem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        /// <summary>
        /// Salvar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Salvar;
        
        /// <summary>
        /// btnCancelar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        /// <summary>
        /// ViewLicencaAmbiental control.
        /// </summary>
        protected global::System.Web.UI.WebControls.View ViewLicencaAmbiental;
        
        /// <summary>
        /// GradeLAO control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GradeLAO;
        
        /// <summary>
        /// Label18 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label18;
        
        /// <summary>
        /// intCodigoDestinoFinal control.
        /// </summary>
        protected global::SILC.Web.forms.INTEIRO7 intCodigoDestinoFinal;
        
        /// <summary>
        /// txtNomeDestinoFinal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNomeDestinoFinal;
        
        /// <summary>
        /// lblFazerUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFazerUpload;
        
        /// <summary>
        /// Label4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label4;
        
        /// <summary>
        /// txtNumeroLicenca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroLicenca;
        
        /// <summary>
        /// UploadDocumento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload UploadDocumento;
        
        /// <summary>
        /// Label20 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label20;
        
        /// <summary>
        /// txtCodigoAtividade control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCodigoAtividade;
        
        /// <summary>
        /// Label19 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label19;
        
        /// <summary>
        /// datPrazoValidade control.
        /// </summary>
        protected global::SILC.Web.forms.DATA datPrazoValidade;
        
        /// <summary>
        /// Label8 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label8;
        
        /// <summary>
        /// txtObs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObs;
        
        /// <summary>
        /// lblMensagemLAO control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensagemLAO;
        
        /// <summary>
        /// btnOk0 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnOk0;
        
        /// <summary>
        /// Button2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button2;
        
        /// <summary>
        /// hifCodigoLAO control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hifCodigoLAO;

        /// <summary>
        /// ibnMudarSernha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnMudarSernha;


        /// <summary>
        /// ibnExcluir control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnExcluir;


        /// <summary>
        /// ibnExcluirLao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ibnExcluirLao;

    }
}
