//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsAvisoColeta
    {
        public int Codigo { get; set; }
        public int CodigoCliente { get; set; }
        public string DataProgramada { get; set; }
        public string DataAviso { get; set; }
        public string eMail { get; set; }
    }
}
