//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsAbastecimento
    {
        public int Sequencial { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public int CodigoCaminhao { get; set; }
        public int CodigoMotorista { get; set; }
        public int Km { get; set; }
        public decimal AcumuladoAnterior { get; set; }
        public decimal AcumuladoAtual { get; set; }
        public decimal Litros { get; set; }
        public decimal DiferencaLitros { get; set; }
        public decimal DiferencaAcumuladaLitros { get; set; }
        public decimal CompraDiesel { get; set; }
        public decimal CompraAculumadaDiesel { get; set; }
        public decimal Estoque { get; set; }
        public decimal PrecoLitro { get; set; }
        public int flagAbastExterno { get; set; }
        public decimal ValorCompraDiesel { get; set; }
    }
}
