//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsAliquotaImpostos
    {
        public int     Sequencial { get; set; }
        public int     CodigoSituacaoTributaria { get; set; }
        public string  CodigoBROOKS { get; set; }
        public string  Descricao { get; set; }
        public decimal ValorLimiteIR { get; set; }
        public decimal AliquotaIR_Retido { get; set; }
        public decimal AliquotaPIS_Retido { get; set; }
        public decimal AliquotaCOFINS_Retido { get; set; }
        public decimal AliquotaContribSocial { get; set; }
        public decimal ValorLimiteCRF { get; set; }
    }
}
