//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsCodigoServicosPrefeitura
    {
        public int Sequencial { get; set; }
        public int Codigo { get; set; }
        public string DescricaoServico { get; set; }
        public string NomePrefeitura { get; set; }
    }
}
