//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsColocaRetira
    {
        public int nuLanc { get; set; }
        public System.DateTime dtColcRetr { get; set; }
        public string nuCaxa { get; set; }
        public string CR { get; set; }
        public int nuOrdm { get; set; }
        public string hsColcRetr { get; set; }
        public string dtARetr { get; set; }
        public string hsARetr { get; set; }
        public int cdObra { get; set; }
        public int cdCamh { get; set; }
    }
}
