//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsContratos
    {
        public int Codigo { get; set; }
        public int CodigoCliente { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public String CNPJ_CPF { get; set; }
        public string DescricaoHistorico { get; set; }
        public int DiaVencimento { get; set; }
        public int NumeroContrato { get; set; }
        public decimal ValorContrato { get; set; }
        public string DataTermino { get; set; }
        public int NumeroCaixasLocadas { get; set; }
        public string DataInicio { get; set; }
        public string DataReajuste { get; set; }
        public string IndiceReajuste { get; set; }
        public string DataRecisao { get; set; }
        public string SituacaoRecisao { get; set; }
        public int EnviarDDR { get; set; }
        public int EnviarCDF { get; set; }
        public int EmiteMTR { get; set; }
        public int EnviarPLANFAT { get; set; }
        public int EnviarRELGER { get; set; }
        public int ApuracaoDe { get; set; }
        public int ApuracaoA { get; set; }
        public int BrooksEnviaPLANFAT { get; set; }
        public int ClienteAprovaPLANFAT { get; set; }
        public int ClienteEnviaOC { get; set; }
        public int ClienteRecebeNFDocs { get; set; }
        public string AniversarioReajuste { get; set; }
        public string DataRegistro { get; set; }
        public string MotivoRescisao { get; set; }
        public int AvisarDiasAntes { get; set; }
        public string Observacao { get; set; }

    }
}
