//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsDestinoFinal
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string CNPJ { get; set; }
        public string Fone { get; set; }
        public string Celular { get; set; }
        public string LocalAterro { get; set; }
        public int EmiteCDF { get; set; }
        public string NomeArqLogo { get; set; }
        public string NomeArqAss { get; set; }
        public string eMail { get; set; }
        public int Ativo { get; set; }
        public int Enviar_emailCDF { get; set; }
        public int Enviar_emailMovResiduos { get; set; }
        public string DataCadastro { get; set; }
        public int CodigoUnidadeDoIMA { get; set; }
    }
}
