//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsEnderecos
    {
        public int    Codigo { get; set; }
        public int    TipoCadastro { get; set; }
        public int    TipoEndereco { get; set; }
        public string endereco { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public int    CodigoMunicipio { get; set; }
        public int    DDD1 { get; set; }
        public string Fone1 { get; set; }
        public int    DDD2 { get; set; }
        public string Fone2 { get; set; }
        public int    DDD3 { get; set; }
        public string Fone3 { get; set; }
        public int    DDDF { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string Contato { get; set; }
        public string InstrucoesFat { get; set; }
        public string Complemento { get; set; }
        public string CargoContato { get; set; }
    }
}
