//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsFatura
    {
        public int NumeroFatura { get; set; }
        public int NumeroLancamento { get; set; }
        public string DataEmissao { get; set; }
        public string CondicaoPagamento { get; set; }
    }
}
