//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsIndicadores
    {
        public int Sequencial { get; set; }
        public string Data { get; set; }
        public decimal Cumprimento { get; set; }
        public decimal ImpossivelAtender { get; set; }
        public decimal FlexibilidadeContrato { get; set; }
        public decimal SolicitacaoCliente { get; set; }
        public decimal ProgramacaoAutomatica { get; set; }
        public decimal CumprimentoManual { get; set; }
        public decimal TotalProgramadoAutomatico { get; set; }
        public decimal TotalProgramadoManual { get; set; }
        public decimal TotalProgramado { get; set; }
        public decimal TotalExecutado { get; set; }
        public decimal TotalExecutadoAutomatico { get; set; }
        public decimal TotalExecutadoManual { get; set; }
        public decimal TotalCancelado { get; set; }
        public decimal TotalCanceladoCliente { get; set; }
        public decimal TotalReprog { get; set; }
        public decimal TotalBloqueioFinanc { get; set; }
        public decimal Cancelamento { get; set; }
        public decimal BloqueioFinanceiro { get; set; }
        public decimal TotalReprogImpossivelAtender { get; set; }
        public decimal TotalReprogFlexibilidade { get; set; }
        public decimal TotalReprogSolicitacaoCliente { get; set; }
        public decimal IndiceReprog { get; set; }
        public decimal TotalReprogOutros { get; set; }
        public decimal IndiceReprogOutros { get; set; }
    }
}
