//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsLancamentoMTR
    {
        public int NumeroLancamento { get; set; }
        public int NumeroMTR { get; set; }
        public int CodigoResiduo { get; set; }
        public decimal Franquia { get; set; }
        public decimal Quantidade { get; set; }
        public decimal ValorUnitario { get; set; }
        public decimal ValorTotal { get; set; }
        public string Deposito { get; set; }
        public string Unidade { get; set; }
        public string Ticket { get; set; }
        public int CodigoAterroSanitario { get; set; }
        public string observacao { get; set; }
        public Int64 NumeroMTRFatima { get; set; }
        public string Motivo { get; set; }
        public string DataDescarga { get; set; }
        public string DescargaMTRe { get; set; }
        public string ControleInternoDescarga { get; set; }

    }
}
