//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsLicencaAmbiental
    {
        public int Codigo { get; set; }
        public int CodigoAterro { get; set; }
        public string NomeDestinoFinal { get; set; }
        public string NumeroLicenca { get; set; }
        public string CodigoAtividade { get; set; }
        public string PrazoValidade { get; set; }
        public string Obs { get; set; }
        public string Arquivo { get; set; }
    }
}
