//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsMapaProgSemanal
    {
        public int Sequencial { get; set; }
        public string Data { get; set; }
        public int DiaDaSemana { get; set; }
        public int CodigoCliente { get; set; }
        public string NomeFantasiaCliente { get; set; }
        public int CodigoCaminhao { get; set; }
        public int CodigoResiduo { get; set; }
        public string ServicoExecutar { get; set; }
    }
}
