//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsProgramacaoDiariaServicos
    {
        public int Sequencial { get; set; }
        public int AnoMesDia { get; set; }
        public int Quadro { get; set; }
        public int Linha { get; set; }
        public string StatusCor { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public string Solicitante { get; set; }
        public int CodigoCliente { get; set; }
        public string NomeCliente { get; set; }
        public string ExecutarServico { get; set; }
        public string DataProgramada { get; set; }
        public string ServicoExecutado { get; set; }
        public int Quantidade { get; set; }
        public int CodigoCaminhao { get; set; }
        public string ModeloCaminhao { get; set; }
        public int CodigoMotorista { get; set; }
        public string NomeMotorista { get; set; }
        public string Observacao { get; set; }
        public int LinhaGrade2 { get; set; }
        public string Unidade { get; set; }
        public int SequencialParaQuadro1 { get; set; }
        public int TipoProgramacao { get; set; }
        public decimal Quantidade2 { get; set; }
        public string Unidade2 { get; set; }
        public string RotaMapa { get; set; }
        public string CorObservacao { get; set; }
        public int OrdemF4 { get; set; }
        public string Origem { get; set; }
        public int CodigoResiduo { get; set; }
        public string DestinoFinal { get; set; }
    }
}
