//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsResiduos 
    {
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public string Unidade { get; set; }
        public string Classe { get; set; }
        public string EstadoFisico { get; set; }
        public string CodigoResiduoManifesto { get; set; }
        public int Ativo { get; set; }
        public string DescricaoReduzida { get; set; }
        public int CodigoDestinoFinal { get; set; }
        public int CodigoGrupoResiduo { get; set; }
        public string TecnologiaAplicada { get; set; }
        public int EhReciclavel { get; set; }
        public int EhServico { get; set; }
        public int CodigoIBAMA { get; set; }
        public string DataCadastro { get; set; }
        public string DescricaoGrupo { get; set; }
        public string DescricaoDestinoFinal { get; set; }
        public clsIBAMA oIbama = new clsIBAMA();
        public decimal M3PorTon { get; set; }
    }
}
