//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsRoteiro
    {
        public int Codigo { get; set; }
        public string Roteiro1 { get; set; }
    }
}
