//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsServicosDesenvolvedor
    {
        public int Codigo { get; set; }
        public string Servico { get; set; }
        public string Detalhamento { get; set; }
        public string Data { get; set; }
        public int Prioridade { get; set; }
        public int Feito { get; set; }
        public string Solicitante { get; set; }
        public int Executando { get; set; }
    }
}
