//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsServicosEventuaisResiduos
    {
        public int Sequencial { get; set; }
        public int SequencialServicosEventuais { get; set; }
        public int CodigoResiduo { get; set; }
        public int CaixaDisponivel { get; set; }
        public string TipoCaixa { get; set; }
        public decimal QuantidadeFranquia { get; set; }
        public string Unidade { get; set; }
        public decimal ValorUnitario { get; set; }
        public string OBS { get; set; }
        public string DataColeta { get; set; }
        public int CodigoCaminhao { get; set; }
        public decimal PercentualReembolso { get; set; }
        public string ServicoRealizar { get; set; }
        public string DispEquipamento { get; set; }
        public int Programado { get; set; }
    }
}
