//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsServicosEventuais
    {
        public int Sequencial { get; set; }
        public int CodigoCliente { get; set; }
        public string DataSolicitacao { get; set; }
        public int CodigoUsuarioSolicitante { get; set; }
        public decimal ValorServico { get; set; }
        public int EnviarDDR { get; set; }
        public int EnviarCDF { get; set; }
    }
}
