//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsCertificadoResiduos
    {
        public int Sequencial { get; set; }
        public int CodigoCliente { get; set; }
        public string MesAno { get; set; }
        public string DataEmissao { get; set; }
        public string PastaArquivo { get; set; }
        public string NomeArquivo { get; set; }
        public int Impressa { get; set; }
    }
}
