//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsContratoResiduos
    {
        public int CodigoContrato { get; set; }
        public int CodigoResiduo { get; set; }
        public string DescricaoReduzidaResiduo { get; set; }
        public int CodigoCliente { get; set; }
        public int CaixaDisponivel { get; set; }
        public string TipoCaixa { get; set; }
        public string FrequenciaColeta { get; set; }
        public string Franquia { get; set; }
        public decimal QuantidadeFranquia { get; set; }
        public decimal ValorUnitario { get; set; }
        public string OBS { get; set; }
        public string DataReajuste { get; set; }
        public string Unidade { get; set; }
        public string Roteiro { get; set; }
        public int CodigoCaminhao { get; set; }
        public string DiasColeta { get; set; }
        public string MesAnoBase { get; set; }
        public string Particularidade { get; set; }
        public string expressao1CobrancaMensal { get; set; }
        public string Franquia1CobrancaMensal { get; set; }
        public string expressao2CobrancaMensal { get; set; }
        public string PeriodicidadeCobrancaMensal { get; set; }
        public decimal ValorUnitarioCobrancaMensal { get; set; }
        public decimal ValorContratoCobrancaMensal { get; set; }
        public decimal ValorExcedenteCobrancaMensal { get; set; }
        public string expressao1CobrancaPeso { get; set; }
        public string expressao2CobrancaPeso { get; set; }
        public string expressao3CobrancaPeso { get; set; }
        public string condicaoCobrancaPeso { get; set; }
        public string expressao4CobrancaPeso { get; set; }
        public decimal FranquiaCobrancaPeso { get; set; }
        public string UnidadeCobrancaPeso { get; set; }

    }
}
