//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsDTR
    {
        public int Sequencial { get; set; }
        public int NumeroLancamento { get; set; }
        public string DataColeta { get; set; }
        public int CodigoClienteColetado { get; set; }
        public string ClienteColetado { get; set; }
        public int CodigoTipoResiduo { get; set; }
        public string TipoResiduo { get; set; }
        public decimal TotalKg { get; set; }
        public string LocalDTR { get; set; }
        public string DataSaida { get; set; }
        public int CodigoLocalEntrega { get; set; }
        public string LocalEntrega { get; set; }
        public int Fechado { get; set; }
        public int Imprimido { get; set; }
        public int NumeroMTR { get; set; }
        public string HoraSaida { get; set; }
        public int CodigoMotorista { get; set; }
        public int CodigoCaminhao { get; set; }
        public int NumeroImpressao { get; set; }
        public int CodigoClienteEmitiuMTR { get; set; }
        public decimal QtNova { get; set; }
        public decimal TotalQtNova { get; set; }
    }
}
