//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class clsDiasDeColeta
    {
        public int    Sequencial { get; set; }      // autoincrement
        public int    CodigoContrato { get; set; }  // pk
        public int    CodigoCliente { get; set; }   // pk
        public int    CodigoResiduo { get; set; }   // pk
        public int    Dia { get; set; }             // pk
	public string DataReajuste { get; set; }    // pk
    }
}
