//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsFuncionarios
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Fone { get; set; }
        public string NomeConta { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string NumeroCTPS { get; set; }
        public string Serie { get; set; }
        public decimal PercentualComissao { get; set; }
        public string DataAdmissao { get; set; }
        public string DataDemissao { get; set; }
    }
}
