//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsLinhasCertificadoResiduos
    {
        public int SequencialCertificadoResiduo { get; set; }
        public int CodigoResiduo { get; set; }
        public decimal QtdeColetaMes { get; set; }
        public string TecnologiaAplicada { get; set; }
        public string DTR { get; set; }
        public int CodigoAterro { get; set; }
    }
}
