//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILCNegocios
{
    using System;
    using System.Collections.Generic;

    public partial class clsNotasFiscais
    {
        public int NumeroNotaFiscal { get; set; }
        public int CodigoCliente { get; set; }
        public string NomeCliente { get; set; }
        public string DataEmissao { get; set; }
        public string Vencimento { get; set; }
        public int NumeroNF { get; set; }
        public decimal PercentualISS { get; set; }
        public string ValorPorExtenso { get; set; }
        public int Cancelada { get; set; }
        public int NFImpressa { get; set; }
        public decimal PercentualIRRF { get; set; }
        public decimal PercentualCRF { get; set; }
        public int DiasEntreVctos { get; set; }
        public int NumeroParcelas { get; set; }
        public int Classificacao { get; set; }
        public int ContaGerencial { get; set; }
        public int TipoDocumento { get; set; }
        public string Historico { get; set; }
        public decimal PercentualINSS { get; set; }
        public decimal ValorBaseINSS { get; set; }
        public int ArquivoParaImportacaoGerado { get; set; }
        public string DataReferencia { get; set; }
        public decimal ValorDescontoIncondicionado { get; set; }
        public string CodigoBROOKS_Impostos { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal ValorISS { get; set; }       
        public decimal ValorPIS { get; set; }
        public decimal ValorCOFINS { get; set; }
        public decimal ValorContrSocial { get; set; }
        public int NumeroRecibo { get; set; }

        private decimal _valorINSS;
        private decimal _valorIRRF;

        public decimal ValorIRRF
        {
            get
            {
                _valorIRRF = ValorTotal * PercentualIRRF / 100;
                return _valorIRRF; 
            }
            set { _valorIRRF = value; }
        }

        public decimal ValorINSS
        {
            get
            {
                _valorINSS = PercentualINSS * ValorBaseINSS / 100; 
                return _valorINSS; 
            }
            set { _valorINSS = value; }
        }

    }
}
